
services:
  server:
    build:
      context: ./server
    container_name: my_server
    ports:
      - "8080:8080"

  
  client:
    build:
      context: ./client
    container_name: my_client
    ports:
      - "3000:3000"
    depends_on:
      - server

